# Generated by Django 5.2.4 on 2025-07-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_news_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="type",
            field=models.CharField(
                choices=[
                    ("supertop", "supertop"),
                    ("top", "top"),
                    ("editors choice", "editors choice"),
                    ("latest", "latest"),
                    ("actual", "actual"),
                    ("video", "video"),
                    ("article", "article"),
                    ("interview", "interview"),
                    ("announcement", "announcement"),
                    ("motivation", "motivation"),
                    ("photo", "photo"),
                ],
                max_length=256,
                verbose_name="type",
            ),
        ),
    ]
