# Generated by Django 5.2.4 on 2025-08-02 13:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_alter_news_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactCreate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Updated at"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Full Name"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.DecimalField(
                        decimal_places=64, max_digits=64, verbose_name="Phone"
                    ),
                ),
                ("theme", models.CharField(max_length=255, verbose_name="Theme")),
                ("message", models.TextField(max_length=255, verbose_name="Message")),
                (
                    "file",
                    models.FileField(upload_to="contact/%Y/%m", verbose_name="file"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameModel(
            old_name="Add",
            new_name="Advertisement",
        ),
        migrations.AddField(
            model_name="news",
            name="content_af",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ar",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ar_dz",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ast",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_az",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_be",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_bg",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_bn",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_br",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_bs",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ca",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ckb",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_cs",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_cy",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_da",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_de",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_dsb",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_el",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_en",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_en_au",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_en_gb",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_eo",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_es",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_es_ar",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_es_co",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_es_mx",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_es_ni",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_es_ve",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_et",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_eu",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_fa",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_fi",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_fr",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_fy",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ga",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_gd",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_gl",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_he",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_hi",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_hr",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_hsb",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_hu",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_hy",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ia",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ig",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ind",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_io",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_is",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_it",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ja",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ka",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_kab",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_kk",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_km",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_kn",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ko",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ky",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_lb",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_lt",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_lv",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_mk",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ml",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_mn",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_mr",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ms",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_my",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_nb",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ne",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_nl",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_nn",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_os",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_pa",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_pl",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_pt",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_pt_br",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ro",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ru",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_sk",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_sl",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_sq",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_sr",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_sr_latn",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_sv",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_sw",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ta",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_te",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_tg",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_th",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_tk",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_tr",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_tt",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_udm",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ug",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_uk",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ur",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_uz",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_vi",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_zh_hans",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_zh_hant",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_af",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ar",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ar_dz",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ast",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_az",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_be",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_bg",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_bn",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_br",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_bs",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ca",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ckb",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_cs",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_cy",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_da",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_de",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_dsb",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_el",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_en",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_en_au",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_en_gb",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_eo",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_es",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_es_ar",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_es_co",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_es_mx",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_es_ni",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_es_ve",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_et",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_eu",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_fa",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_fi",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_fr",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_fy",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ga",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_gd",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_gl",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_he",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_hi",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_hr",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_hsb",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_hu",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_hy",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ia",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ig",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ind",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_io",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_is",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_it",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ja",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ka",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_kab",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_kk",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_km",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_kn",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ko",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ky",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_lb",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_lt",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_lv",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_mk",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ml",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_mn",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_mr",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ms",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_my",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_nb",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ne",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_nl",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_nn",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_os",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_pa",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_pl",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_pt",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_pt_br",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ro",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ru",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_sk",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_sl",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_sq",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_sr",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_sr_latn",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_sv",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_sw",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ta",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_te",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_tg",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_th",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_tk",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_tr",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_tt",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_udm",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ug",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_uk",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ur",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_uz",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_vi",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_zh_hans",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_zh_hant",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_af",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_ar",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_ar_dz",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_ast",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_az",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_be",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_bg",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_bn",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_br",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_bs",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_ca",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_ckb",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_cs",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_cy",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_da",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_de",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_dsb",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_el",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_en",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_en_au",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_en_gb",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_eo",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_es",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_es_ar",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_es_co",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_es_mx",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_es_ni",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_es_ve",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_et",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_eu",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_fa",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_fi",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_fr",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_fy",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_ga",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_gd",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_gl",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_he",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_hi",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_hr",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_hsb",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_hu",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_hy",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_ia",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_ig",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_ind",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_io",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_is",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_it",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_ja",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_ka",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_kab",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_kk",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_km",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_kn",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_ko",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_ky",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_lb",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_lt",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_lv",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_mk",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_ml",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_mn",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_mr",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_ms",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_my",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_nb",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_ne",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_nl",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_nn",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_os",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_pa",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_pl",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_pt",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_pt_br",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_ro",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_ru",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_sk",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_sl",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_sq",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_sr",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_sr_latn",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_sv",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_sw",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_ta",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_te",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_tg",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_th",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_tk",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_tr",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_tt",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_udm",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_ug",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_uk",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_ur",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_uz",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_vi",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_zh_hans",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="title_zh_hant",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_af",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_ar",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_ar_dz",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_ast",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_az",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_be",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_bg",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_bn",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_br",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_bs",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_ca",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_ckb",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_cs",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_cy",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_da",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_de",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_dsb",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_el",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_en",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_en_au",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_en_gb",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_eo",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_es",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_es_ar",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_es_co",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_es_mx",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_es_ni",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_es_ve",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_et",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_eu",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_fa",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_fi",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_fr",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_fy",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_ga",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_gd",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_gl",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_he",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_hi",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_hr",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_hsb",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_hu",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_hy",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_ia",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_ig",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_ind",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_io",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_is",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_it",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_ja",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_ka",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_kab",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_kk",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_km",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_kn",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_ko",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_ky",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_lb",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_lt",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_lv",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_mk",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_ml",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_mn",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_mr",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_ms",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_my",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_nb",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_ne",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_nl",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_nn",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_os",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_pa",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_pl",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_pt",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_pt_br",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_ro",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_ru",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_sk",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_sl",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_sq",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_sr",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_sr_latn",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_sv",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_sw",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_ta",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_te",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_tg",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_th",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_tk",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_tr",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_tt",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_udm",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_ug",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_uk",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_ur",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_uz",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_vi",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_zh_hans",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="newstag",
            name="title_zh_hant",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_af",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_ar",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_ar_dz",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_ast",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_az",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_be",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_bg",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_bn",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_br",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_bs",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_ca",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_ckb",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_cs",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_cy",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_da",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_de",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_dsb",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_el",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_en",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_en_au",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_en_gb",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_eo",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_es",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_es_ar",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_es_co",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_es_mx",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_es_ni",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_es_ve",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_et",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_eu",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_fa",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_fi",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_fr",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_fy",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_ga",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_gd",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_gl",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_he",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_hi",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_hr",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_hsb",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_hu",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_hy",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_ia",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_ig",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_ind",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_io",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_is",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_it",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_ja",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_ka",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_kab",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_kk",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_km",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_kn",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_ko",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_ky",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_lb",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_lt",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_lv",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_mk",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_ml",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_mn",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_mr",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_ms",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_my",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_nb",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_ne",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_nl",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_nn",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_os",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_pa",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_pl",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_pt",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_pt_br",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_ro",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_ru",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_sk",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_sl",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_sq",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_sr",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_sr_latn",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_sv",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_sw",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_ta",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_te",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_tg",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_th",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_tk",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_tr",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_tt",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_udm",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_ug",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_uk",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_ur",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_uz",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_vi",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_zh_hans",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="region",
            name="title_zh_hant",
            field=models.CharField(max_length=256, null=True, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="type",
            field=models.CharField(
                choices=[
                    ("video", "video"),
                    ("article", "article"),
                    ("interview", "interview"),
                    ("announcement", "announcement"),
                    ("motivation", "motivation"),
                    ("supertop", "supertop"),
                    ("top", "top"),
                    ("editors choice", "editors choice"),
                    ("latest", "latest"),
                    ("actual", "actual"),
                    ("photo", "photo"),
                ],
                max_length=256,
                verbose_name="type",
            ),
        ),
    ]
