# Generated by Django 5.2.4 on 2025-08-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_contactcreate_rename_add_advertisement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactcreate",
            name="phone",
            field=models.CharField(max_length=255, verbose_name="Phone number"),
        ),
    ]
